name: Deploy Application

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # MUST COME BEFORE COMPOSER INSTALL
      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.1'
          extensions: mbstring, xml, ctype, iconv, mysql, gd
          tools: composer:v2

      - name: Install PHP Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Discover Laravel Packages
        run: php artisan package:discover --ansi

      - name: Generate Spatie TypeScript Types
        run: |
          mkdir -p resources/js/generated
          php artisan typescript:transform
          php artisan structure-scouts:cache

      - name: Generate Wayfinder Routes and Form Variants
        run: php artisan wayfinder:generate --with-form

      - name: Install Node & Build Assets
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: |
          npm ci
          npm run build

      - name: Ensure Target Build Directory Exists on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: mkdir -p /var/www/TransportSystem/public/build

      - name: Deploy Build Artifact to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "public/build/*"
          target: "/var/www/TransportSystem/public/build"
          strip_components: 2

      - name: Clear View Cache on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: php /var/www/TransportSystem/artisan optimize:clear